# This workflow runs the tests

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Run the tests
      - name: Run tests
        run: ./gradlew test
